pp_hbao.name=HBAO
pp_hbao.info=Horizon-Based Ambient Occlusion by AniCator and Drew Watts from Estranged Act 1 of Alan Edwardes.
pp_hbao.enable=Enable
pp_hbao.upsample=Upsampling
pp_hbao.upsample.help=Render HBAO as half resolution and then upsample it to native size. Require restart of map.
pp_hbao.radius=Occlusion Radius
pp_hbao.anglebias=Angle Bias
pp_hbao.intensity=Occlusion Intensity
pp_hbao.debug=Debug mode
pp_hbao.translucent=Pre Translucent hook of render
pp_hbao.high=High
pp_hbao.medium=Medium
pp_hbao.low=Low
pp_hbao.quality=Quality
pp_hbao.thickness=Wall Thickness Ratio
pp_hbao.gi=Enable GI Color Bleeding
pp_hbao.gi_strength=GI Strength
